apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: ofirc/proxy:latest
        command: ["/usr/bin/tinyproxy", "-d"]
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  selector:
    app: proxy
  ports:
  - port: 8888
    targetPort: 8888
  type: ClusterIP
