apiVersion: apps/v1
kind: Deployment
metadata:
  name: stunnel
  labels:
    app: stunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stunnel
  template:
    metadata:
      labels:
        app: stunnel
    spec:
      containers:
      - name: stunnel
        image: ofirc/stunnel:latest
        command: ["/usr/bin/stunnel"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: stunnel
spec:
  selector:
    app: stunnel
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
